server:
  port: 20001
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3307/bms?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      auto-commit: false
      maximum-pool-size: 1000
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug